version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  auth-service:
    build:
      context: ./Auth_Service_BE
      dockerfile: Dockerfile
    ports:
      - "6002:6002"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 6002
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6002"]
      interval: 10s
      timeout: 5s
      retries: 5

  problem-service:
    build:
      context: ./Problem_Service_BE
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVER_PORT: 6000
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000"]
      interval: 10s
      timeout: 5s
      retries: 5

  execution-service:
    build:
      context: ./Execution_Service_BE
      dockerfile: Dockerfile
    ports:
      - "6001:6001"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVICE_PROBLEM_URL: http://problem-service:6000/
      SERVER_PORT: 6001
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./Execution_Service_BE/UserSubmittedCodes:/app/UserSubmittedCodes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6001"]
      interval: 10s
      timeout: 5s
      retries: 5

  code-war:
    build:
      context: ./Code_War_FE
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVICE_PROBLEM_URL: http://problem-service:6000/
      SERVICE_EXECUTION_URL: http://execution-service:6001/
      SERVICE_AUTH_URL: http://auth-service:6002/
      SERVER_PORT: 8081
    depends_on:
      mysql:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      problem-service:
        condition: service_healthy

volumes:
  mysql-data:
