FROM openjdk
WORKDIR /app

COPY /Problem_Service_BE-0.0.1-SNAPSHOT.jar /app/Problem_Service_BE-0.0.1-SNAPSHOT.jar

EXPOSE 6001

ENTRYPOINT ["java", "-jar", "Problem_Service_BE-0.0.1-SNAPSHOT.jar"]



